name: Deploy Bot

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add Server to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 185.193.66.70 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh root@185.193.66.70 << 'EOF'
          cd /root/alb70bot

          echo "⬇️ Pulling latest version..."
          git pull

          echo "🐍 Checking Python syntax..."
          python3 -m compileall .

          echo "🔄 Restarting bot..."
          systemctl restart alb70bot

          echo "⏳ Waiting..."
          sleep 3

          echo "📋 Bot status:"
          systemctl status alb70bot --no-pager

          echo "✅ Deployment completed."
          EOF
