name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add Host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 185.193.66.70 >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh root@185.193.66.70 "
            cd /root/alb70bot &&
            git pull &&
            systemctl restart alb70bot
          "
