name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secret
        run: |
          if [ -z "${{ secrets.SSH_KEY }}" ]; then
            echo "SECRET IS EMPTY"
          else
            echo "SECRET EXISTS"
          fi
